config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show update edit destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save

    redirect_to articles_path
  end

  def edit; end

  def show; end

  def update
    @article.update(article_params)

    redirect_to articles_path
  end

  def destroy
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= link_to "My Articles", articles_path %>

<%= form_for(article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>Update My Article</h1>
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>My Articles</h1>
<ul>
<% @articles.each do |article| %>
<li>
<h4> <%= link_to article.title, article_path(article) %></h4>
 <%= link_to 'Update', edit_article_path(article) %>
 <%= button_to "Delete", article_path(article), method: :delete, data: { 'turbo-confirm': "Are you sure?" } %>
</li>
<% end %>
</ul>

 <%= link_to 'Add New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>Add New Article</h1>
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title%></h1>
<p><%= @article.content%></p>


<%= link_to "Back to tasks", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>